import sqlite3

# Define connection and cursor
connection = sqlite3.connect("MaskIT.db")
cursor = connection.cursor()

# Enable foreign keys
cursor.execute("PRAGMA foreign_keys = ON;")

# Create unverified database
c = """CREATE TABLE IF NOT EXISTS UNVERIFIED(
ID_JWT TEXT,
PASS_JWT TEXT,
EMAIL_JWT TEXT,
NAME_JWT TEXT
);"""

cursor.execute(c)

# Create user table
c = """CREATE TABLE IF NOT EXISTS USERS(
USER_ID TEXT PRIMARY KEY,
PASSWORD TEXT,
SALT TEXT,
NAME TEXT,
EMAIL TEXT NOT NULL,
PHONE TEXT,
CREATED_TIME DATETIME
);"""

cursor.execute(c)

# Create Post table
c = """CREATE TABLE IF NOT EXISTS POSTS(
POST_ID TEXT PRIMARY KEY,
USER_ID TEXT,
CAPTION TEXT,
TAGS TEXT,
LOCATION TEXT,
IMAGE_LINK TEXT,
CREATED_TIME DATETIME,
SCORE INT,
BODY TEXT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);"""

cursor.execute(c)

# Create Comment table
c = """CREATE TABLE IF NOT EXISTS COMMENTS(
COMMENT_ID TEXT PRIMARY KEY,
USER_ID TEXT,
POST_ID TEXT,
CREATED_TIME DATETIME,
COMMENT_TEXT TEXT,
REPLY_ID INT,
SCORE INT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID),
FOREIGN KEY (REPLY_ID) REFERENCES COMMENTS(REPLY_ID) ON DELETE CASCADE
);"""

cursor.execute(c)

# Create Reaction table
c = """CREATE TABLE IF NOT EXISTS REACTIONS(
TYPE INT,
USER_ID TEXT,
POST_ID TEXT,
COMMENT_ID TEXT,
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID) ON DELETE CASCADE
);"""

cursor.execute(c)

# Commit and close
connection.commit()
connection.close()
